### ISSUE TITLE
This exception is very often

### ISSUE THREAD

**Issue by pevghenii** [blueboy-tm/flutter_v2ray#42]
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=V2RAY_CONNECTION_INFO flg=0x10 (has extras) } in com.github.blueboytm.flutter_v2ray.v2ray.V2rayController$1@5eb67d6
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1764)
       at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.app.ActivityThread.main(ActivityThread.java:8396)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

**Comment by blueboy-tm** [comment]
The bug was fixed
